export default {
    // USERS ACTIONS
    USERS: 'USERS',
    USERS_RESPONSE: 'USERS_RESPONSE',

    USER_BY_ID: 'USER_BY_ID',
    USER_BY_ID_RESPONSE: 'USER_BY_ID_RESPONSE',

    USER_REQUEST: 'USER_REQUEST',
    USER_ERROR: 'USER_ERROR',

    // AUTH ACTIONS
    LOGIN: 'LOGIN',
    LOGIN_RESPONSE: 'LOGIN_RESPONSE',

    SIGNUP: 'SIGNUP',
    SIGNUP_RESPONSE: 'SIGNUP_RESPONSE',

    LOGOUT: 'LOGOUT',
    LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',

    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_ERROR: 'AUTH_ERROR',

    // PHOTO ACTIONS
    PHOTOS: 'PHOTOS',
    PHOTOS_RESPONSE: 'PHOTOS_RESPONSE',

    PHOTO_BY_ID: 'PHOTO_BY_ID',
    PHOTO_BY_ID_RESPONSE: 'PHOTO_BY_ID_RESPONSE',

    PHOTO_REQUEST: 'PHOTO_REQUEST',
    PHOTO_ERROR: 'PHOTO_ERROR',

    // COMMENT ACTIONS
    COMMENTS: 'COMMENTS',
    COMMENTS_RESPONSE: 'COMMENTS_RESPONSE',

    COMMENT_ADD: 'COMMENT_ADD',
    COMMENT_ADD_RESPONSE: 'COMMENT_ADD_RESPONSE',

    COMMENT_REQUEST: 'COMMENT_REQUEST',
    COMMENT_ERROR: 'COMMENT_ERROR',
}
